version: "3.8"

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 123456
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
    restart: unless-stopped
